apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    require-tls: 'spi'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/development/spi
    repoURL: https://github.com/solarperformanceinsight/spi-deploy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mysql
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/development/mysql
    repoURL: https://github.com/solarperformanceinsight/spi-deploy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-redis
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/development/redis
    repoURL: https://github.com/solarperformanceinsight/spi-deploy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
