apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    require-tls: 'spi'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/production/spi
    repoURL: https://github.com/yas11r/spi-deploy
    targetRevision: v0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/production/mysql
    repoURL: https://github.com/yas11r/spi-deploy
    targetRevision: v0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/production/redis
    repoURL: https://github.com/yas11r/spi-deploy
    targetRevision: v0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
