apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: solarperformanceinsight
  labels:
    app: solarperformanceinsight
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dev.solarperformanceinsight.org
    http:
      paths:
      - path: /
        backend:
          serviceName: solarperformanceinsight
          servicePort: http
  tls:
  - hosts:
      - dev.solarperformanceinsight.org
    secretName: spi-tls
