apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  state: dev
namespace: development
resources:
- ../../base
- ingress.yaml
- migration-job.yaml
images:
- digest: sha256:57725bdb67ab2581787efb16cc7ff57d1a4a74bc6b2c4868c5d68234fc195ac1
  name: quay.io/solarperformanceinsight/solarperformanceinsight

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "spi-mysql.development.svc"
  target:
    group: batch
    kind: Job
    name: schema-migration
    version: v1
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "spi-mysql.development.svc"
  target:
    group: apps
    kind: Deployment
    name: solarperformanceinsight
    version: v1
