apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  state: dev
namespace: development
resources:
- ../../base
- ingress.yaml
- migration-job.yaml
images:
- digest: sha256:a3c257c67682a6dc823bfe7dbee20296d3c594d4d4581ebd6d235e249fbf4c1d
  name: quay.io/solarperformanceinsight/solarperformanceinsight

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "spi-mysql.development.svc"
  target:
    group: batch
    kind: Job
    name: schema-migration
    version: v1
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "spi-mysql.development.svc"
  target:
    group: apps
    kind: Deployment
    name: solarperformanceinsight
    version: v1
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "spi-redis.development.svc"
  target:
    group: apps
    kind: Deployment
    name: solarperformanceinsight
    version: v1
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "spi-mysql.development.svc"
  target:
    group: apps
    kind: Deployment
    name: spi-rq-worker
    version: v1
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "spi-redis.development.svc"
  target:
    group: apps
    kind: Deployment
    name: spi-rq-worker
    version: v1
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "spi-mysql.development.svc"
  target:
    group: apps
    kind: Deployment
    name: spi-queue-sync
    version: v1
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "spi-redis.development.svc"
  target:
    group: apps
    kind: Deployment
    name: spi-queue-sync
    version: v1
