apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  state: dev
namespace: development
resources:
- ../../base
- ingress.yaml
images:
- digest: sha256:8853219feae292a8dd777221d8151443f7192e106fbe874e94ce0c26d3619773
  name: quay.io/solarperformanceinsight/solarperformanceinsight
