apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  state: dev
namespace: development
resources:
- ../../base
- ingress.yaml
images:
- digest: sha256:37f350bd041c93fae306857ea72b6a39a01a59280b453e91a564f9c2cb88e0ed
  name: quay.io/solarperformanceinsight/solarperformanceinsight
