apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  state: dev
namespace: development
resources:
- ../../base
- ingress.yaml
- migration-job.yaml
images:
- digest: sha256:741f9a8e3d19ad4a1a78ba2fb3d59ed71d8c569234943c71db6c048595e1e084
  name: quay.io/solarperformanceinsight/solarperformanceinsight

patchesJSON6902:
  - target:
      group: batch
      version: v1
      kind: Job
      name: schema-migration
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "spi-mysql.development.svc"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: solarperformanceinsight
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "spi-mysql.development.svc"
