apiVersion: batch/v1
kind: Job
metadata:
  name: schema-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: quay.io/solarperformanceinsight/solarperformanceinsight:main
          command:
            - /opt/app-root/bin/migrate
          env:
          - name: MYSQL_HOST
            value: 'spi-mysql'
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: spi-mysql
          - name: ALTER_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: alter-user-password
                name: spi-mysql
  backoffLimit: 3
  ttlSecondsAfterFinished: 60
