apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  state: prod
namespace: production
resources:
  - ../../../base/redis
images:
- name: redis
  digest: sha256:cd015a1d1e6a485ee71a656a17a6a35d32819175b67fa6ee3c47b6fb6141cbe1
patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/data/0/key
      value: /k8ssecrets/production/redis/users.acl
    - op: replace
      path: /spec/data/1/key
      value: /k8ssecrets/production/redis/user
    - op: replace
      path: /spec/data/2/key
      value: /k8ssecrets/production/redis/password
  target:
    group: kubernetes-client.io
    kind: ExternalSecret
    name: spi-redis
    version: v1
