apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: spi-redis
spec:
  backendType: systemManager
  data:
    - name: users.acl
      key: /k8ssecrets/dev/redis/users.acl
    - name: user
      key: /k8ssecrets/dev/redis/user
    - name: password
      key: /k8ssecrets/dev/redis/password
