apiVersion: v1
kind: Service
metadata:
  name: spi-redis
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
