global:
  resolve_timeout: 5m
  http_config: {}
route:
  receiver: default
  routes:
  - receiver: deadmansswitch
    match:
      alertname: Watchdog
    repeat_interval: 5m
  - receiver: slack_critical
    match:
      severity: critical
  - receiver: slack_warning
    match:
      severity: warning
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: default
- name: slack_critical
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: spi-critical
    send_resolved: true
- name: slack_warning
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: spi-warning
    send_resolved: true
- name: deadmansswitch
  webhook_configs:
  - send_resolved: false
    http_config: {}
    url: https://pf2wj1kal0.execute-api.us-west-2.amazonaws.com/prod
templates: []
