apiVersion: v1
kind: ConfigMap
metadata:
  name: spi-mysql
data:
  my-cnf: |
    [mysqld]
    datadir=/var/lib/mysql/data
    socket=/tmp/mysql.sock
    mysqlx_socket=/tmp/mysqlx.sock
    default-time-zone='+00:00'
    innodb_file_per_table
