apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app: solarperformanceinsight
    component: db
resources:
  - service.yaml
  - secret.yaml
  - configmap.yaml
  - statefulset.yaml
