apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: spi-mysql
spec:
  backendType: systemManager
  data:
    - name: alter-user-password
      key: /k8ssecrets/dev/mysql/apiuser-password
    - name: database-root-password
      key: /k8ssecrets/dev/mysql/root-password
