apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solarperformanceinsight
  name: solarperformanceinsight
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: solarperformanceinsight
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: solarperformanceinsight
    spec:
      initContainers:
      - name: copystatic
        command:
          - sh
          - -c
          - "cp -r /opt/app-root/static/* /static/."
        image: quay.io/solarperformanceinsight/solarperformanceinsight
        volumeMounts:
          - mountPath: /static
            name: static-files
      containers:
      - name: api
        image: quay.io/solarperformanceinsight/solarperformanceinsight
        command:
          - sh
          - -c
          - |
            uvicorn solarperformanceinsight_api.main:app \
              --host 0.0.0.0 \
              --port 8079 \
              --proxy-headers \
              --forwarded-allow-ips '*' \
              --root-path /api \
              --workers 4 \
              --log-config /conf/logging.json
        ports:
          - containerPort: 8079
            protocol: TCP
            name: apihttp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          httpGet:
            path: /ping
            port: apihttp
          initialDelaySeconds:
          timeoutSeconds: 5
          periodSeconds: 15
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            memory: 1024Mi
        volumeMounts:
          - mountPath: /conf/logging.json
            name: uvicorn-log-config
            subPath: logging.json
      - name: nginx
        image: nginx:1.19
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 1
          timeoutSeconds: 5
          periodSeconds: 15
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            memory: 300Mi
        volumeMounts:
          - mountPath: /static
            name: static-files
          - mountPath: /etc/nginx/conf.d/spi.conf
            name: nginx-conf
            subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: static-files
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-config
        - name: uvicorn-log-config
          configMap:
            name: uvicorn-log-config
