apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solarperformanceinsight
  name: solarperformanceinsight
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: solarperformanceinsight
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: solarperformanceinsight
    spec:
      initContainers:
      - name: copystatic
        command:
          - sh
          - -c
          - "cp -r /opt/app-root/static/* /static/."
        image: quay.io/solarperformanceinsight/solarperformanceinsight
        volumeMounts:
          - mountPath: /static
            name: static-files
      containers:
      - name: staticfiles
        image: nginx:1.19
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 1
          timeoutSeconds: 5
          periodSeconds: 15
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            memory: 300Mi
        volumeMounts:
          - mountPath: /static
            name: static-files
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-conf
            subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: static-files
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-config
