apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solarperformanceinsight
  name: solarperformanceinsight
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: solarperformanceinsight
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: solarperformanceinsight
    spec:
      containers:
      - name: staticfiles
        env:
          - name: NGINX_PORT
            value: 8080
        image: nginx:1.19
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 15
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            memory: 300Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
