apiVersion: v1
kind: ConfigMap
data:
  nginx.conf: |
    server {
        listen       8080;
        server_name  _;
        index  index.html index.htm;

        location / {
            root /static;
        }
    }
metadata:
  name: nginx-config
