apiVersion: v1
kind: Service
metadata:
  labels:
    app: solarperformanceinsight
  name: solarperformanceinsight
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app: solarperformanceinsight
  sesionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
