apiVersion: v1
kind: Service
metadata:
  labels:
    app: solarperformanceinsight
  name: solarperformanceinsight
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: solarperformanceinsight
    component: api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
